name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      - run: npm i -g npm@latest
      - run: npm i --no-optional
      - run: npm run test
